#! /bin/bash

wget -q -O update.py https://raw.githubusercontent.com/chromium/chromium/master/tools/clang/scripts/update.py > /dev/null 2>&1
CLANG_REVISION=$(cat update.py | grep CLANG_REVISION | head -n 1 | cut -d "'" -f 2)
echo ${CLANG_REVISION}
rm -rf update.py
